services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  my.twig.extension:
      class: BlogBundle\Extensions\Twig\Helpers
      arguments:
        doctrine: "@doctrine"
      tags:
        - { name: twig.extension }