BlogBundle\Entity\Etiqueta:
    properties:
        nombre:
            - NotBlank: {message: "El campo nombre de la etiqueta no puede estar vacío"}
            - Length: {min: 2, minMessage: "El nombre tiene que tener más de dos caracteres"}