BlogBundle\Entity\Categoria:
    type: entity
    table: categoria
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    oneToMany:
        entrada:
            targetEntity: Entrada
            mappedBy: categoria
            cascade: ["persist"]
    lifecycleCallbacks: {  }
