BlogBundle\Entity\EntradaEtiqueta:
    type: entity
    table: entrada_etiqueta
    indexes:
        fk_entrada_has_etiqueta_etiqueta1_idx:
            columns:
                - etiqueta_id
        fk_entrada_has_etiqueta_entrada1_idx:
            columns:
                - entrada_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        entrada:
            targetEntity: Entrada
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: entradaEtiqueta
            joinColumns:
                entrada_id:
                    referencedColumnName: id
            orphanRemoval: false
        etiqueta:
            targetEntity: Etiqueta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: entradaEtiqueta
            joinColumns:
                etiqueta_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
