BlogBundle\Entity\Entrada:
    type: entity
    table: entrada
    repositoryClass: BlogBundle\Repository\EntradaRepository
    indexes:
        fk_entrada_usuario_idx:
            columns:
                - usuario_id
        fk_entrada_categoria1_idx:
            columns:
                - categoria_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        contenido:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        status:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        categoria:
            targetEntity: Categoria
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: entrada
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: entrada
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        entradaEtiqueta:
            targetEntity: EntradaEtiqueta
            mappedBy: entrada
            cascade: ["persist"]
    lifecycleCallbacks: {  }
